### ISSUE TITLE
Just tried and the mod is not working

### ISSUE THREAD

**Issue by asd2006208** [nedsociety/MonsterTrainConsole#1]
Hello dear nedsociety, I recently subscribed this mod on Steam and it's not working. Pressed ` key but nothing happens. Is it just me or the mod simply not supporting the game?

**Comment by nedsociety** [comment]
![image](https://user-images.githubusercontent.com/11943013/165200070-04af178b-a5bf-4501-abc1-125989f4c9aa.png)

Works well for me. Did you enable both Mod Loader (BepInEx) and Trainworks on settings?

**Comment by asd2006208** [comment]
Yes sir, I enabled all the mods in Mod Settings. Dun know what to do XD
[image: capture.PNG]

**Comment by nedsociety** [comment]
Can you provide `%userprofile%\LocalLow\Shiny Shoe\MonsterTrain\Player.log` file?

**Comment by asd2006208** [comment]
Sure, absolutely. Please see the attachment.

**Comment by nedsociety** [comment]
I guess you're attaching it on your email client? I don't see any (including capture.png file for the previous post).

Try uploading it on the github page: https://github.com/nedsociety/MonsterTrainConsole/issues/1

(you may drag & drop the file into the box to upload a file)

**Comment by asd2006208** [comment]
Sorry mate didn't realize that. Here comes pic and the file
![capture](https://user-images.githubusercontent.com/104403354/165441324-6a8f4f72-1f40-479d-b96f-b414bce4dfc6.PNG)
[Player.log](https://github.com/nedsociety/MonsterTrainConsole/files/8568844/Player.log)
.

**Comment by nedsociety** [comment]
Your Player.log file looks as if it doesn't have any mods enabled at all. Are other mods (Stoker Deck Editor, Upgrade Champions, etc.) working?

**Comment by asd2006208** [comment]
Unfortunately, none of them are working even I turned on the mods in the Mod Settings

**Comment by nedsociety** [comment]
Closed as it's not a MTConsole issue.

For general MT modding issues I'd recommend `#modding-discussion` channel at [MT Discord](https://discord.com/invite/monstertrain).

**Comment by asd2006208** [comment]
Thanks for all your times and works mate. Have a good one :)

**Comment by nedsociety** [comment]
Well we're basically just moving the discussion to somewhere else 🙄 I'm also active in the MT discord.

**Comment by asd2006208** [comment]
lol, hope to see you there. Btw, is there anything else I need to do to activate the mods other than turning them on in the Mod Settings?
